// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDFww5yyI6rMEHSXqOsP6hv_m6pBt-wE',
    appId: '1:36914786904:web:014f4f6e62a9803842502d',
    messagingSenderId: '36914786904',
    projectId: 'dimatest-fa192',
    authDomain: 'dimatest-fa192.firebaseapp.com',
    storageBucket: 'dimatest-fa192.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGQqlKnwYQFVOuueUw0_xks10c87VxkI',
    appId: '1:36914786904:android:fd4b2f107c09637942502d',
    messagingSenderId: '36914786904',
    projectId: 'dimatest-fa192',
    storageBucket: 'dimatest-fa192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8yblyesPc-09bye4ZF9KlO95G6RhhlmA',
    appId: '1:36914786904:ios:7c005f1b34b84d6542502d',
    messagingSenderId: '36914786904',
    projectId: 'dimatest-fa192',
    storageBucket: 'dimatest-fa192.appspot.com',
    iosBundleId: 'com.example.prva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8yblyesPc-09bye4ZF9KlO95G6RhhlmA',
    appId: '1:36914786904:ios:0a762833f77347ce42502d',
    messagingSenderId: '36914786904',
    projectId: 'dimatest-fa192',
    storageBucket: 'dimatest-fa192.appspot.com',
    iosBundleId: 'com.example.prva.RunnerTests',
  );
}
